def top_10_table(self):
    self.buttonGame.place_forget()
    self.buttonTop10.place_forget()
    self.buttonScoreHistory.place_forget()
    self.buttonBack1 = MyButton(text="Back to Main menu", command=self.back_from_top)
    self.labelTop10 = MyLabel(text="Top 10 scores")
    self.buttonBack1.place(x=635, y=450, anchor="center")
    self.labelTop10.place(x=635, y=70, anchor="center")
    self.tree2 = ttk.Treeview(column=("c1", "c2", "c3", "c4"), show="headings")
    self.tree2.column("#1", anchor=CENTER, width=150)
    self.tree2.heading("#1", text="Date")
    self.tree2.column("#2", anchor=CENTER, width=150)
    self.tree2.heading("#2", text="Name")
    self.tree2.column("#3", anchor=CENTER, width=150)
    self.tree2.heading("#3", text="Last name")
    self.tree2.column("#4", anchor=CENTER, width=100)
    self.tree2.heading("#4", text="Score")
    self.tree2.place(x=625, y=250, anchor="center")
    self.rows = top_10_scores()
    for row in self.rows:
        self.tree2.insert("", END, values=row)

        def back_from_top(self):
            self.labelTop10.place_forget()
            self.tree2.place_forget()
            self.buttonBack1.place_forget()
            self.buttonGame.place(x=435, y=300, anchor="center")
            self.buttonTop10.place(x=635, y=300, anchor="center")
            self.buttonScoreHistory.place(x=835, y=300, anchor="center")
